name: Deploy AquaSense

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: cd services && mvn clean install
    
    - name: Run tests
      run: cd services && mvn test
    
    - name: Build Docker images
      run: docker-compose build
    
    - name: Push to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
        docker-compose push
    
    - name: Deploy to EKS
      run: |
        aws eks update-kubeconfig --region us-east-1 --name aquasense-cluster
        kubectl apply -f infra/kubernetes/
